name: "ESP32 Dev Controller V4"
board: "ESP32 Dev Controller V4"

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 0
  pulse_us: 4
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 300
    acceleration_mm_per_sec2: 20
    max_travel_mm: 400
    soft_limits: true
    homing:
      cycle: 3
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 200
      feed_mm_per_min: 50
      settle_ms: 250
      seek_scale: 1.1
      feed_scale: 1.1
    
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.4:low:pu
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.14
        step_pin: gpio.13:low
    motor1:
      null_motor:

  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 200
    acceleration_mm_per_sec2: 10
    max_travel_mm: 550
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 200
      feed_mm_per_min: 50
      settle_ms: 250
      seek_scale: 1.1
      feed_scale: 1.1

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.16:low:pu
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.26
        step_pin: gpio.27:low
    motor1:
      null_motor:

  z:
    steps_per_mm: 80
    max_rate_mm_per_min: 300
    acceleration_mm_per_sec2: 20
    max_travel_mm: 400
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 0
      positive_direction: false
      seek_mm_per_min: 200
      feed_mm_per_min: 50
      settle_ms: 250
      seek_scale: 1.1
      feed_scale: 1.1

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.17:low:pu
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        direction_pin: gpio.33
        step_pin: gpio.25:low
    motor1:
      null_motor:

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

start:
  must_home: false
  check_limits: false

PWM:
  pwm_hz: 5000
  output_pin: gpio.2:low
  enable_pin: gpio.21
  direction_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0% 10000=100%
